name = "enterkorea"
main = "worker-site/index.js"
compatibility_date = "2026-04-19"
workers_dev = true
preview_urls = false

[[routes]]
pattern = "kimpboard.com"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
