// Auto-generated by Startup Once/시황파악 QVGM 포트폴리오.py — DO NOT EDIT.

export type QvgmPortfolioHolding = {
  ticker: string;
  name: string;
  weight_pct: number;
  reason: string;
};

export type QvgmPortfolioBest = {
  name: string;
  style: string;
  holdings: QvgmPortfolioHolding[];
  metrics: { cagr: number; sharpe: number; max_dd: number; composite: number };
};

export type QvgmPortfolioCategory = {
  label: string;
  best: QvgmPortfolioBest;
  alternativesCount: number;
};

export const qvgmPortfolioGeneratedAt = "2026-04-27T23:40:08.093311";

export const qvgmPortfolio_kr: QvgmPortfolioCategory | null = null;

export const qvgmPortfolio_krUs: QvgmPortfolioCategory | null = null;

export const qvgmPortfolio_us: QvgmPortfolioCategory = {
  "label": "미국 ETF (US-listed)",
  "best": {
    "name": "성장 편향형 포트폴리오",
    "style": "기술주 및 모멘텀 중심의 공격적 자본 차익 추구",
    "holdings": [
      {
        "ticker": "QQQM",
        "weight_pct": 30.0,
        "reason": "나스닥 100 지수를 추종하며 미국 핵심 기술주 전반에 투자 (QQQ 대비 저렴한 보수)",
        "name": "Nasdaq-100 (Mini)"
      },
      {
        "ticker": "SMH",
        "weight_pct": 20.0,
        "reason": "높은 수익률과 훌륭한 샤프 지수를 기록 중인 글로벌 반도체 산업에 집중 투자",
        "name": "Semiconductor (VanEck)"
      },
      {
        "ticker": "VUG",
        "weight_pct": 20.0,
        "reason": "미국 대형 성장주 전반에 투자하여 기술주 외의 성장 동력 확보",
        "name": "Vanguard Growth"
      },
      {
        "ticker": "XLK",
        "weight_pct": 15.0,
        "reason": "S&P 500 내 핵심 IT 섹터 비중을 확대하여 기술주 주도 장세 극대화",
        "name": "Tech Select Sector"
      },
      {
        "ticker": "MTUM",
        "weight_pct": 15.0,
        "reason": "최근 주가 상승 추세가 강한 모멘텀 주식들을 편입하여 초과 수익 추구",
        "name": "MSCI USA Momentum"
      }
    ],
    "metrics": {
      "cagr": 55.2,
      "sharpe": 1.36,
      "max_dd": -38.04,
      "composite": 0.6158
    }
  },
  "alternativesCount": 4
};
