// Auto-generated by Startup Once/시황파악 QVGM 포트폴리오.py — DO NOT EDIT.
// (Placeholder — 첫 실행 전까지 빈 값 유지. Python 스크립트가 매월 1일 03:00 KST 갱신.)

export type QvgmPortfolioHolding = {
  ticker: string;
  name: string;
  weight_pct: number;
  reason: string;
};

export type QvgmPortfolioBest = {
  name: string;
  style: string;
  holdings: QvgmPortfolioHolding[];
  metrics: { cagr: number; sharpe: number; max_dd: number; composite: number };
};

export type QvgmPortfolioCategory = {
  label: string;
  best: QvgmPortfolioBest;
  alternativesCount: number;
};

export const qvgmPortfolioGeneratedAt: string = '';

export const qvgmPortfolio_kr: QvgmPortfolioCategory | null = null;
export const qvgmPortfolio_krUs: QvgmPortfolioCategory | null = null;
export const qvgmPortfolio_us: QvgmPortfolioCategory | null = null;
